# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.dockets_public_list_get_response import DocketsPublicListGetResponse

class TestDocketsPublicListGetResponse(unittest.TestCase):
    """DocketsPublicListGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocketsPublicListGetResponse:
        """Test DocketsPublicListGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocketsPublicListGetResponse`
        """
        model = DocketsPublicListGetResponse()
        if include_optional:
            return DocketsPublicListGetResponse(
                success = True,
                failure_message = '',
                cache_key_name = '',
                list_items = [
                    valis.models.docket_public_list_get_response.DocketPublicListGetResponse(
                        docket_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        meeting_time = '', 
                        docket_number = 56, 
                        description = '', 
                        is_public = True, 
                        docket_type_id = 56, 
                        docket_type = '', 
                        chamber_code = '', 
                        session_id = 56, 
                        session_code = '', 
                        vote_room_id = 56, 
                        comments = '', 
                        committee_id = 56, 
                        committee_name = '', 
                        parent_committee_name = '', 
                        pending_change = True, 
                        reference_number = '', 
                        is_proforma = True, 
                        deletion_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        docket_id = 56, 
                        docket_files = [
                            valis.models.docket_file_public_get_response.DocketFilePublicGetResponse(
                                calendar_file_id = 56, 
                                calendar_id = 56, 
                                file_url = '', 
                                text_format_id = 56, 
                                is_generated = True, 
                                is_public = True, 
                                is_active = True, )
                            ], )
                    ]
            )
        else:
            return DocketsPublicListGetResponse(
        )
        """

    def testDocketsPublicListGetResponse(self):
        """Test DocketsPublicListGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
