# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.docket_file_public_get_response import DocketFilePublicGetResponse

class TestDocketFilePublicGetResponse(unittest.TestCase):
    """DocketFilePublicGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocketFilePublicGetResponse:
        """Test DocketFilePublicGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocketFilePublicGetResponse`
        """
        model = DocketFilePublicGetResponse()
        if include_optional:
            return DocketFilePublicGetResponse(
                calendar_file_id = 56,
                calendar_id = 56,
                file_url = '',
                text_format_id = 56,
                is_generated = True,
                is_public = True,
                is_active = True
            )
        else:
            return DocketFilePublicGetResponse(
                text_format_id = 56,
        )
        """

    def testDocketFilePublicGetResponse(self):
        """Test DocketFilePublicGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
