# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.owner_type_reference_response1 import OwnerTypeReferenceResponse1

class TestOwnerTypeReferenceResponse1(unittest.TestCase):
    """OwnerTypeReferenceResponse1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OwnerTypeReferenceResponse1:
        """Test OwnerTypeReferenceResponse1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OwnerTypeReferenceResponse1`
        """
        model = OwnerTypeReferenceResponse1()
        if include_optional:
            return OwnerTypeReferenceResponse1(
                owner_type_id = '',
                owner_type = ''
            )
        else:
            return OwnerTypeReferenceResponse1(
        )
        """

    def testOwnerTypeReferenceResponse1(self):
        """Test OwnerTypeReferenceResponse1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
