# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.vote_types import VoteTypes

class TestVoteTypes(unittest.TestCase):
    """VoteTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VoteTypes:
        """Test VoteTypes
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VoteTypes`
        """
        model = VoteTypes()
        if include_optional:
            return VoteTypes(
                success = True,
                failure_message = '',
                cache_key_name = '',
                list_items = [
                    valis.models.vote_type.VoteType(
                        name = '', 
                        id = 56, )
                    ]
            )
        else:
            return VoteTypes(
        )
        """

    def testVoteTypes(self):
        """Test VoteTypes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
