# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.legislations_references_response import LegislationsReferencesResponse

class TestLegislationsReferencesResponse(unittest.TestCase):
    """LegislationsReferencesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LegislationsReferencesResponse:
        """Test LegislationsReferencesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LegislationsReferencesResponse`
        """
        model = LegislationsReferencesResponse()
        if include_optional:
            return LegislationsReferencesResponse(
                success = True,
                failure_message = '',
                cache_key_name = '',
                list_items = [
                    valis.models.legislation_references_response.LegislationReferencesResponse(
                        legislation_status_id = 56, 
                        name = '', 
                        display_name = '', 
                        legislation_version_id = 56, )
                    ]
            )
        else:
            return LegislationsReferencesResponse(
        )
        """

    def testLegislationsReferencesResponse(self):
        """Test LegislationsReferencesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
