# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.create_public_user_request import CreatePublicUserRequest

class TestCreatePublicUserRequest(unittest.TestCase):
    """CreatePublicUserRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePublicUserRequest:
        """Test CreatePublicUserRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePublicUserRequest`
        """
        model = CreatePublicUserRequest()
        if include_optional:
            return CreatePublicUserRequest(
                hashed_word = '',
                first_name = '',
                last_name = '',
                password = '0123456789'
            )
        else:
            return CreatePublicUserRequest(
                hashed_word = '',
                password = '0123456789',
        )
        """

    def testCreatePublicUserRequest(self):
        """Test CreatePublicUserRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
