# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.committee_role_reference import CommitteeRoleReference

class TestCommitteeRoleReference(unittest.TestCase):
    """CommitteeRoleReference unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommitteeRoleReference:
        """Test CommitteeRoleReference
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommitteeRoleReference`
        """
        model = CommitteeRoleReference()
        if include_optional:
            return CommitteeRoleReference(
                committee_role_id = 56,
                title = '',
                chamber_code = '0'
            )
        else:
            return CommitteeRoleReference(
        )
        """

    def testCommitteeRoleReference(self):
        """Test CommitteeRoleReference"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
