# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.contact_type_reference_response import ContactTypeReferenceResponse

class TestContactTypeReferenceResponse(unittest.TestCase):
    """ContactTypeReferenceResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContactTypeReferenceResponse:
        """Test ContactTypeReferenceResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContactTypeReferenceResponse`
        """
        model = ContactTypeReferenceResponse()
        if include_optional:
            return ContactTypeReferenceResponse(
                contact_type_id = 56,
                owner_type_id = 56,
                owner_type = '',
                contact_type = ''
            )
        else:
            return ContactTypeReferenceResponse(
        )
        """

    def testContactTypeReferenceResponse(self):
        """Test ContactTypeReferenceResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
