# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.committee_action_response import CommitteeActionResponse

class TestCommitteeActionResponse(unittest.TestCase):
    """CommitteeActionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommitteeActionResponse:
        """Test CommitteeActionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommitteeActionResponse`
        """
        model = CommitteeActionResponse()
        if include_optional:
            return CommitteeActionResponse(
                committee_action_id = 56,
                description = '',
                event_code = '',
                is_complete = True
            )
        else:
            return CommitteeActionResponse(
        )
        """

    def testCommitteeActionResponse(self):
        """Test CommitteeActionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
