# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.legislations_session_response import LegislationsSessionResponse

class TestLegislationsSessionResponse(unittest.TestCase):
    """LegislationsSessionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LegislationsSessionResponse:
        """Test LegislationsSessionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LegislationsSessionResponse`
        """
        model = LegislationsSessionResponse()
        if include_optional:
            return LegislationsSessionResponse(
                success = True,
                failure_message = '',
                cache_key_name = '',
                list_items = [
                    valis.models.legislation_session_response.LegislationSessionResponse(
                        legislation_id = 56, 
                        legislation_number = '', 
                        description = '', 
                        chamber_code = '0', 
                        legislation_type_code = '0', 
                        legislation_key = 56, 
                        legislation_status = '', 
                        patrons = [
                            valis.models.patron.Patron(
                                legislation_id = 56, 
                                legislation_text_id = 56, 
                                chamber_code = '', 
                                member_id = 56, 
                                member_number = '', 
                                patron_type_id = 56, 
                                name = '', 
                                display_name = '', 
                                member_display_name = '', 
                                patron_display_name = '', 
                                legislation_number = '', 
                                sequence = 56, 
                                is_introducing = True, 
                                by_request = True, )
                            ], )
                    ]
            )
        else:
            return LegislationsSessionResponse(
        )
        """

    def testLegislationsSessionResponse(self):
        """Test LegislationsSessionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
