# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.amendment_response import AmendmentResponse

class TestAmendmentResponse(unittest.TestCase):
    """AmendmentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AmendmentResponse:
        """Test AmendmentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AmendmentResponse`
        """
        model = AmendmentResponse()
        if include_optional:
            return AmendmentResponse(
                legislation_id = 56,
                legislation_text_id = 56,
                legislation_version_id = 56,
                legislation_version = '',
                text_disposition_id = 56,
                text_disposition = '',
                is_active = True,
                is_public = True,
                document_code = '',
                chamber_code = '',
                description = '',
                ld_number = '',
                version_date = ''
            )
        else:
            return AmendmentResponse(
        )
        """

    def testAmendmentResponse(self):
        """Test AmendmentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
