# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.create_partner_request import CreatePartnerRequest

class TestCreatePartnerRequest(unittest.TestCase):
    """CreatePartnerRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreatePartnerRequest:
        """Test CreatePartnerRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreatePartnerRequest`
        """
        model = CreatePartnerRequest()
        if include_optional:
            return CreatePartnerRequest(
                hashed_word = '',
                contact_name = '',
                organization_name = '',
                url = '',
                phone = '',
                eula_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return CreatePartnerRequest(
                hashed_word = '',
                contact_name = '',
                phone = '',
        )
        """

    def testCreatePartnerRequest(self):
        """Test CreatePartnerRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
