# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.public_schedule_response import PublicScheduleResponse

class TestPublicScheduleResponse(unittest.TestCase):
    """PublicScheduleResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicScheduleResponse:
        """Test PublicScheduleResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicScheduleResponse`
        """
        model = PublicScheduleResponse()
        if include_optional:
            return PublicScheduleResponse(
                display_sequence = 56,
                owner_id = 56,
                owner_name = '',
                schedule_type_id = 56,
                schedule_type = '',
                vote_room_id = 56,
                room_description = '',
                schedule_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                schedule_time = '',
                comments = '',
                is_cancelled = True,
                is_public = True,
                link_url = '',
                schedule_id = 56,
                version_sequence = 56
            )
        else:
            return PublicScheduleResponse(
        )
        """

    def testPublicScheduleResponse(self):
        """Test PublicScheduleResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
