# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.sessions_shallow_public_get_response import SessionsShallowPublicGetResponse

class TestSessionsShallowPublicGetResponse(unittest.TestCase):
    """SessionsShallowPublicGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionsShallowPublicGetResponse:
        """Test SessionsShallowPublicGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionsShallowPublicGetResponse`
        """
        model = SessionsShallowPublicGetResponse()
        if include_optional:
            return SessionsShallowPublicGetResponse(
                success = True,
                failure_message = '',
                cache_key_name = '',
                list_items = [
                    valis.models.session_shallow_public_get_response.SessionShallowPublicGetResponse(
                        session_code = '', 
                        display_name = '', 
                        session_year = 56, 
                        session_type = '', 
                        start_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        is_default = True, 
                        is_active = True, 
                        session_id = 56, )
                    ]
            )
        else:
            return SessionsShallowPublicGetResponse(
        )
        """

    def testSessionsShallowPublicGetResponse(self):
        """Test SessionsShallowPublicGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
