# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.agencies_response import AgenciesResponse

class TestAgenciesResponse(unittest.TestCase):
    """AgenciesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgenciesResponse:
        """Test AgenciesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgenciesResponse`
        """
        model = AgenciesResponse()
        if include_optional:
            return AgenciesResponse(
                success = True,
                failure_message = '',
                cache_key_name = '',
                list_items = [
                    valis.models.agency_response.AgencyResponse(
                        identity_id = 56, 
                        agency_name = '', 
                        abbreviation = '', 
                        agency_number = '', 
                        branch = '', )
                    ]
            )
        else:
            return AgenciesResponse(
        )
        """

    def testAgenciesResponse(self):
        """Test AgenciesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
