# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.api.heart_beat_api import HeartBeatApi


class TestHeartBeatApi(unittest.TestCase):
    """HeartBeatApi unit test stubs"""

    def setUp(self) -> None:
        self.api = HeartBeatApi()

    def tearDown(self) -> None:
        pass

    def test_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_authentication_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for authentication_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_calendar_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for calendar_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_committee_legislation_referral_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for committee_legislation_referral_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_communication_file_generation_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for communication_file_generation_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_contact_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for contact_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_by_member_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_by_member_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_collections_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_collections_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_communications_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_communications_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_event_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_event_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_file_generation_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_file_generation_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_patron_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_patron_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_subject_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_subject_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_summary_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_summary_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_text_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_text_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_legislation_version_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for legislation_version_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_member_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for member_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_member_vote_search_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for member_vote_search_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_members_by_committee_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for members_by_committee_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_minutes_book_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for minutes_book_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_organization_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for organization_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass

    def test_partner_authentication_api_heartbeat_heartbeatasync_get(self) -> None:
        """Test case for partner_authentication_api_heartbeat_heartbeatasync_get

        Checks service health
        """
        pass


if __name__ == '__main__':
    unittest.main()
