# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.public_committee_response import PublicCommitteeResponse

class TestPublicCommitteeResponse(unittest.TestCase):
    """PublicCommitteeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PublicCommitteeResponse:
        """Test PublicCommitteeResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PublicCommitteeResponse`
        """
        model = PublicCommitteeResponse()
        if include_optional:
            return PublicCommitteeResponse(
                name = '',
                committee_number = '',
                chamber_code = '0',
                session_code = '',
                twitter_handle = '',
                twitter_email = '',
                parent_committee_id = 56,
                service_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                service_begin_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                effective_begin_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                effective_end_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                abbreviation = '',
                description = '',
                meeting_note = '',
                pending_change = True,
                sub_pending_change = True,
                is_public = True,
                agenda_url = '',
                committee_id = 56,
                committee_files = [
                    valis.models.public_committee_file_response.PublicCommitteeFileResponse(
                        committee_id = 56, 
                        file_url = '', 
                        text_format_id = 56, 
                        is_generated = True, 
                        is_public = True, 
                        is_active = True, 
                        description = '', 
                        committee_file_id = 56, )
                    ]
            )
        else:
            return PublicCommitteeResponse(
                name = '',
                committee_number = '',
                chamber_code = '0',
        )
        """

    def testPublicCommitteeResponse(self):
        """Test PublicCommitteeResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
