# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.legislation_text_action_response import LegislationTextActionResponse

class TestLegislationTextActionResponse(unittest.TestCase):
    """LegislationTextActionResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LegislationTextActionResponse:
        """Test LegislationTextActionResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LegislationTextActionResponse`
        """
        model = LegislationTextActionResponse()
        if include_optional:
            return LegislationTextActionResponse(
                legislation_text_action_id = 56,
                description = '',
                event_code = ''
            )
        else:
            return LegislationTextActionResponse(
        )
        """

    def testLegislationTextActionResponse(self):
        """Test LegislationTextActionResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
