# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from valis.models.calendar_public_list_get_response import CalendarPublicListGetResponse

class TestCalendarPublicListGetResponse(unittest.TestCase):
    """CalendarPublicListGetResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CalendarPublicListGetResponse:
        """Test CalendarPublicListGetResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CalendarPublicListGetResponse`
        """
        model = CalendarPublicListGetResponse()
        if include_optional:
            return CalendarPublicListGetResponse(
                calendar_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                meeting_time = '',
                calendar_number = 56,
                description = '',
                is_public = True,
                calendar_type = '',
                calendar_type_id = 56,
                chamber_code = '',
                session_id = 56,
                session_code = '',
                vote_room_id = 56,
                room_description = '',
                comments = '',
                pending_change = True,
                reference_number = '',
                is_proforma = True,
                deletion_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                calendar_id = 56,
                calendar_files = [
                    valis.models.calendar_file_base_model.CalendarFileBaseModel(
                        calendar_file_id = 56, 
                        calendar_id = 56, 
                        file_url = '', 
                        text_format_id = 56, 
                        is_generated = True, 
                        is_public = True, 
                        is_active = True, )
                    ],
                calendar_comments = [
                    valis.models.calendar_comment_public_get_response.CalendarCommentPublicGetResponse(
                        calendar_id = 56, 
                        comment = '', 
                        sequence = 56, 
                        deletion_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        calendar_comment_id = 56, )
                    ]
            )
        else:
            return CalendarPublicListGetResponse(
                calendar_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                calendar_type = '',
                session_id = 56,
                calendar_id = 56,
        )
        """

    def testCalendarPublicListGetResponse(self):
        """Test CalendarPublicListGetResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
