# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from valis.models.agenda_public_get_response import AgendaPublicGetResponse
from typing import Optional, Set
from typing_extensions import Self

class CalendarCategoryPublicGetResponse(BaseModel):
    """
    Calendar Category Public Get Response
    """ # noqa: E501
    calendar_id: Optional[StrictInt] = Field(default=None, description="Calendar ID", alias="CalendarID")
    calendar_category_type_id: Optional[StrictInt] = Field(default=None, description="Calendar Category Type ID", alias="CalendarCategoryTypeID")
    category_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="Category Code", alias="CategoryCode")
    category_type: Optional[Annotated[str, Field(strict=True, max_length=25)]] = Field(default=None, description="Category Type", alias="CategoryType")
    description: Optional[Annotated[str, Field(strict=True, max_length=500)]] = Field(default=None, description="Calendar Category Type Description", alias="Description")
    plural_description: Optional[StrictStr] = Field(default=None, description="Calendar Category Type Description if plural", alias="PluralDescription")
    sequence: Optional[StrictInt] = Field(default=None, description="Calendar Category Sequence", alias="Sequence")
    display_type: Optional[StrictBool] = Field(default=None, description="Display Calendar Category Type", alias="DisplayType")
    is_legislation_category: Optional[StrictBool] = Field(default=None, description="Legislation Indicator", alias="IsLegislationCategory")
    is_print: Optional[StrictBool] = Field(default=None, description="Printable Indicator", alias="IsPrint")
    calendar_category_id: Optional[StrictInt] = Field(default=None, description="Calendar Category unique identifier", alias="CalendarCategoryID")
    agendas: Optional[List[AgendaPublicGetResponse]] = Field(default=None, description="Listing of Agendas", alias="Agendas")
    __properties: ClassVar[List[str]] = ["CalendarID", "CalendarCategoryTypeID", "CategoryCode", "CategoryType", "Description", "PluralDescription", "Sequence", "DisplayType", "IsLegislationCategory", "IsPrint", "CalendarCategoryID", "Agendas"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CalendarCategoryPublicGetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in agendas (list)
        _items = []
        if self.agendas:
            for _item_agendas in self.agendas:
                if _item_agendas:
                    _items.append(_item_agendas.to_dict())
            _dict['Agendas'] = _items
        # set to None if calendar_id (nullable) is None
        # and model_fields_set contains the field
        if self.calendar_id is None and "calendar_id" in self.model_fields_set:
            _dict['CalendarID'] = None

        # set to None if calendar_category_type_id (nullable) is None
        # and model_fields_set contains the field
        if self.calendar_category_type_id is None and "calendar_category_type_id" in self.model_fields_set:
            _dict['CalendarCategoryTypeID'] = None

        # set to None if category_code (nullable) is None
        # and model_fields_set contains the field
        if self.category_code is None and "category_code" in self.model_fields_set:
            _dict['CategoryCode'] = None

        # set to None if category_type (nullable) is None
        # and model_fields_set contains the field
        if self.category_type is None and "category_type" in self.model_fields_set:
            _dict['CategoryType'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['Description'] = None

        # set to None if plural_description (nullable) is None
        # and model_fields_set contains the field
        if self.plural_description is None and "plural_description" in self.model_fields_set:
            _dict['PluralDescription'] = None

        # set to None if sequence (nullable) is None
        # and model_fields_set contains the field
        if self.sequence is None and "sequence" in self.model_fields_set:
            _dict['Sequence'] = None

        # set to None if display_type (nullable) is None
        # and model_fields_set contains the field
        if self.display_type is None and "display_type" in self.model_fields_set:
            _dict['DisplayType'] = None

        # set to None if is_legislation_category (nullable) is None
        # and model_fields_set contains the field
        if self.is_legislation_category is None and "is_legislation_category" in self.model_fields_set:
            _dict['IsLegislationCategory'] = None

        # set to None if is_print (nullable) is None
        # and model_fields_set contains the field
        if self.is_print is None and "is_print" in self.model_fields_set:
            _dict['IsPrint'] = None

        # set to None if calendar_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.calendar_category_id is None and "calendar_category_id" in self.model_fields_set:
            _dict['CalendarCategoryID'] = None

        # set to None if agendas (nullable) is None
        # and model_fields_set contains the field
        if self.agendas is None and "agendas" in self.model_fields_set:
            _dict['Agendas'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CalendarCategoryPublicGetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CalendarID": obj.get("CalendarID"),
            "CalendarCategoryTypeID": obj.get("CalendarCategoryTypeID"),
            "CategoryCode": obj.get("CategoryCode"),
            "CategoryType": obj.get("CategoryType"),
            "Description": obj.get("Description"),
            "PluralDescription": obj.get("PluralDescription"),
            "Sequence": obj.get("Sequence"),
            "DisplayType": obj.get("DisplayType"),
            "IsLegislationCategory": obj.get("IsLegislationCategory"),
            "IsPrint": obj.get("IsPrint"),
            "CalendarCategoryID": obj.get("CalendarCategoryID"),
            "Agendas": [AgendaPublicGetResponse.from_dict(_item) for _item in obj["Agendas"]] if obj.get("Agendas") is not None else None
        })
        return _obj


