# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CommitteeActionResponse(BaseModel):
    """
    CommitteeAction Response Model for getting Committee Action reference list
    """ # noqa: E501
    committee_action_id: Optional[StrictInt] = Field(default=None, description="Committee Action ID", alias="CommitteeActionID")
    description: Optional[Annotated[str, Field(strict=True, max_length=100)]] = Field(default=None, description="Description of the Action", alias="Description")
    event_code: Optional[Annotated[str, Field(strict=True, max_length=10)]] = Field(default=None, description="EventCode of the Action", alias="EventCode")
    is_complete: Optional[StrictBool] = Field(default=None, description="IsComplete yes/no", alias="IsComplete")
    __properties: ClassVar[List[str]] = ["CommitteeActionID", "Description", "EventCode", "IsComplete"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CommitteeActionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if committee_action_id (nullable) is None
        # and model_fields_set contains the field
        if self.committee_action_id is None and "committee_action_id" in self.model_fields_set:
            _dict['CommitteeActionID'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['Description'] = None

        # set to None if event_code (nullable) is None
        # and model_fields_set contains the field
        if self.event_code is None and "event_code" in self.model_fields_set:
            _dict['EventCode'] = None

        # set to None if is_complete (nullable) is None
        # and model_fields_set contains the field
        if self.is_complete is None and "is_complete" in self.model_fields_set:
            _dict['IsComplete'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CommitteeActionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "CommitteeActionID": obj.get("CommitteeActionID"),
            "Description": obj.get("Description"),
            "EventCode": obj.get("EventCode"),
            "IsComplete": obj.get("IsComplete")
        })
        return _obj


