# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from valis.models.patron_partner_get_response import PatronPartnerGetResponse
from typing import Optional, Set
from typing_extensions import Self

class DocketItemPublicGetResponse(BaseModel):
    """
    Docket Item Public Get Response which includes ID
    """ # noqa: E501
    sequence: Optional[StrictInt] = Field(default=None, description="Sequence of Docket(Committee Calendar) Items", alias="Sequence")
    docket_id: Optional[StrictInt] = Field(default=None, description="Docket(Committee Calendar) ID", alias="DocketID")
    category_type: Optional[StrictStr] = Field(default=None, description="Category Type", alias="CategoryType")
    docket_category_id: Optional[StrictInt] = Field(default=None, description="Docket(Committee Calendar) Category ID", alias="DocketCategoryID")
    category_code: Optional[StrictStr] = Field(default=None, description="Category Code", alias="CategoryCode")
    description: Optional[StrictStr] = Field(default=None, description="Docket Category Description", alias="Description")
    legislation_id: Optional[StrictInt] = Field(default=None, description="Legislation ID", alias="LegislationID")
    legislation_number: Optional[StrictStr] = Field(default=None, description="Legislation Number", alias="LegislationNumber")
    legislation_description: Optional[StrictStr] = Field(default=None, description="Legislation Description", alias="LegislationDescription")
    ld_number: Optional[StrictStr] = Field(default=None, description="Legislation Draft (LD)Number", alias="LDNumber")
    summary: Optional[StrictStr] = Field(default=None, description="Legislation Summary", alias="Summary")
    draft_title: Optional[StrictStr] = Field(default=None, description="Draft Title", alias="DraftTitle")
    is_active: Optional[StrictBool] = Field(default=None, description="is Agenda Item active", alias="IsActive")
    calendar_category_template_id: Optional[StrictInt] = Field(default=None, description="Calendar Category Template ID", alias="CalendarCategoryTemplateID")
    communication_id: Optional[StrictInt] = Field(default=None, description="Communication ID", alias="CommunicationID")
    committee_id: Optional[StrictInt] = Field(default=None, description="CommitteeID", alias="CommitteeID")
    candidate_date: Optional[datetime] = Field(default=None, description="Candidate Date", alias="CandidateDate")
    docket_item_id: Optional[StrictInt] = Field(default=None, description="Unique Identifier for Docket Item ID", alias="DocketItemID")
    patrons: Optional[List[PatronPartnerGetResponse]] = Field(default=None, description="list of Patrons for an Docket Item", alias="Patrons")
    __properties: ClassVar[List[str]] = ["Sequence", "DocketID", "CategoryType", "DocketCategoryID", "CategoryCode", "Description", "LegislationID", "LegislationNumber", "LegislationDescription", "LDNumber", "Summary", "DraftTitle", "IsActive", "CalendarCategoryTemplateID", "CommunicationID", "CommitteeID", "CandidateDate", "DocketItemID", "Patrons"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DocketItemPublicGetResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in patrons (list)
        _items = []
        if self.patrons:
            for _item_patrons in self.patrons:
                if _item_patrons:
                    _items.append(_item_patrons.to_dict())
            _dict['Patrons'] = _items
        # set to None if sequence (nullable) is None
        # and model_fields_set contains the field
        if self.sequence is None and "sequence" in self.model_fields_set:
            _dict['Sequence'] = None

        # set to None if docket_id (nullable) is None
        # and model_fields_set contains the field
        if self.docket_id is None and "docket_id" in self.model_fields_set:
            _dict['DocketID'] = None

        # set to None if category_type (nullable) is None
        # and model_fields_set contains the field
        if self.category_type is None and "category_type" in self.model_fields_set:
            _dict['CategoryType'] = None

        # set to None if docket_category_id (nullable) is None
        # and model_fields_set contains the field
        if self.docket_category_id is None and "docket_category_id" in self.model_fields_set:
            _dict['DocketCategoryID'] = None

        # set to None if category_code (nullable) is None
        # and model_fields_set contains the field
        if self.category_code is None and "category_code" in self.model_fields_set:
            _dict['CategoryCode'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['Description'] = None

        # set to None if legislation_id (nullable) is None
        # and model_fields_set contains the field
        if self.legislation_id is None and "legislation_id" in self.model_fields_set:
            _dict['LegislationID'] = None

        # set to None if legislation_number (nullable) is None
        # and model_fields_set contains the field
        if self.legislation_number is None and "legislation_number" in self.model_fields_set:
            _dict['LegislationNumber'] = None

        # set to None if legislation_description (nullable) is None
        # and model_fields_set contains the field
        if self.legislation_description is None and "legislation_description" in self.model_fields_set:
            _dict['LegislationDescription'] = None

        # set to None if ld_number (nullable) is None
        # and model_fields_set contains the field
        if self.ld_number is None and "ld_number" in self.model_fields_set:
            _dict['LDNumber'] = None

        # set to None if summary (nullable) is None
        # and model_fields_set contains the field
        if self.summary is None and "summary" in self.model_fields_set:
            _dict['Summary'] = None

        # set to None if draft_title (nullable) is None
        # and model_fields_set contains the field
        if self.draft_title is None and "draft_title" in self.model_fields_set:
            _dict['DraftTitle'] = None

        # set to None if is_active (nullable) is None
        # and model_fields_set contains the field
        if self.is_active is None and "is_active" in self.model_fields_set:
            _dict['IsActive'] = None

        # set to None if calendar_category_template_id (nullable) is None
        # and model_fields_set contains the field
        if self.calendar_category_template_id is None and "calendar_category_template_id" in self.model_fields_set:
            _dict['CalendarCategoryTemplateID'] = None

        # set to None if communication_id (nullable) is None
        # and model_fields_set contains the field
        if self.communication_id is None and "communication_id" in self.model_fields_set:
            _dict['CommunicationID'] = None

        # set to None if committee_id (nullable) is None
        # and model_fields_set contains the field
        if self.committee_id is None and "committee_id" in self.model_fields_set:
            _dict['CommitteeID'] = None

        # set to None if candidate_date (nullable) is None
        # and model_fields_set contains the field
        if self.candidate_date is None and "candidate_date" in self.model_fields_set:
            _dict['CandidateDate'] = None

        # set to None if docket_item_id (nullable) is None
        # and model_fields_set contains the field
        if self.docket_item_id is None and "docket_item_id" in self.model_fields_set:
            _dict['DocketItemID'] = None

        # set to None if patrons (nullable) is None
        # and model_fields_set contains the field
        if self.patrons is None and "patrons" in self.model_fields_set:
            _dict['Patrons'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DocketItemPublicGetResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Sequence": obj.get("Sequence"),
            "DocketID": obj.get("DocketID"),
            "CategoryType": obj.get("CategoryType"),
            "DocketCategoryID": obj.get("DocketCategoryID"),
            "CategoryCode": obj.get("CategoryCode"),
            "Description": obj.get("Description"),
            "LegislationID": obj.get("LegislationID"),
            "LegislationNumber": obj.get("LegislationNumber"),
            "LegislationDescription": obj.get("LegislationDescription"),
            "LDNumber": obj.get("LDNumber"),
            "Summary": obj.get("Summary"),
            "DraftTitle": obj.get("DraftTitle"),
            "IsActive": obj.get("IsActive"),
            "CalendarCategoryTemplateID": obj.get("CalendarCategoryTemplateID"),
            "CommunicationID": obj.get("CommunicationID"),
            "CommitteeID": obj.get("CommitteeID"),
            "CandidateDate": obj.get("CandidateDate"),
            "DocketItemID": obj.get("DocketItemID"),
            "Patrons": [PatronPartnerGetResponse.from_dict(_item) for _item in obj["Patrons"]] if obj.get("Patrons") is not None else None
        })
        return _obj


