# coding: utf-8

"""
    merged spec

    merged spec

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, Optional
from typing import Optional, Set
from typing_extensions import Self

class VoteItemResponse(BaseModel):
    """
    Information for a Vote Item
    """ # noqa: E501
    ld_number: Optional[StrictStr] = Field(default=None, description="Legislation LD #", alias="LDNumber")
    legislation_version_id: Optional[StrictInt] = Field(default=None, description="Unique identifier for Legislation VersionID", alias="LegislationVersionID")
    legislation_version: Optional[StrictStr] = Field(default=None, description="Legislation Version name", alias="LegislationVersion")
    legislation_text_id: Optional[StrictInt] = Field(default=None, description="Unique identifier for Legislation Text", alias="LegislationTextID")
    document_code: Optional[StrictStr] = Field(default=None, description="Document Code", alias="DocumentCode")
    description: Optional[StrictStr] = Field(default=None, description="Legislation description", alias="Description")
    committee_id: Optional[StrictInt] = Field(default=None, description="Unique identifier for Committee", alias="CommitteeID")
    __properties: ClassVar[List[str]] = ["LDNumber", "LegislationVersionID", "LegislationVersion", "LegislationTextID", "DocumentCode", "Description", "CommitteeID"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VoteItemResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if ld_number (nullable) is None
        # and model_fields_set contains the field
        if self.ld_number is None and "ld_number" in self.model_fields_set:
            _dict['LDNumber'] = None

        # set to None if legislation_version_id (nullable) is None
        # and model_fields_set contains the field
        if self.legislation_version_id is None and "legislation_version_id" in self.model_fields_set:
            _dict['LegislationVersionID'] = None

        # set to None if legislation_version (nullable) is None
        # and model_fields_set contains the field
        if self.legislation_version is None and "legislation_version" in self.model_fields_set:
            _dict['LegislationVersion'] = None

        # set to None if legislation_text_id (nullable) is None
        # and model_fields_set contains the field
        if self.legislation_text_id is None and "legislation_text_id" in self.model_fields_set:
            _dict['LegislationTextID'] = None

        # set to None if document_code (nullable) is None
        # and model_fields_set contains the field
        if self.document_code is None and "document_code" in self.model_fields_set:
            _dict['DocumentCode'] = None

        # set to None if description (nullable) is None
        # and model_fields_set contains the field
        if self.description is None and "description" in self.model_fields_set:
            _dict['Description'] = None

        # set to None if committee_id (nullable) is None
        # and model_fields_set contains the field
        if self.committee_id is None and "committee_id" in self.model_fields_set:
            _dict['CommitteeID'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VoteItemResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "LDNumber": obj.get("LDNumber"),
            "LegislationVersionID": obj.get("LegislationVersionID"),
            "LegislationVersion": obj.get("LegislationVersion"),
            "LegislationTextID": obj.get("LegislationTextID"),
            "DocumentCode": obj.get("DocumentCode"),
            "Description": obj.get("Description"),
            "CommitteeID": obj.get("CommitteeID")
        })
        return _obj


